[{'IndividualID': 2148118,
  'Name': 'ELLIOTT CAMEL-TOUEG',
  'Organization': {'OrganizationID': 289624,
   'Name': 'LOTFUL REALTY',
   'Address': {'AddressText': '58 HAMPTON AVE|OTTAWA, Ontario K1Y0N2',
    'PermitShowAddress': True},
   'Phones': [{'PhoneType': 'Telephone',
     'PhoneNumber': '724-6222',
     'AreaCode': '613',
     'PhoneTypeId': '1'}],
   'Emails': [{'ContactId': '574540573'}],
   'OrganizationType': 'Firm',
   'Designation': 'Brokerage',
   'HasEmail': True,
   'PermitFreetextEmail': True,
   'PermitShowListingLink': True,
   'RelativeDetailsURL': '/office/firm/289624/lotful-realty-58-hampton-ave-ottawa-ontario-k1y0n2',
   'PhotoLastupdate': '2025-02-25 11:21:00 PM'},
  'Phones': [{'PhoneType': 'Telephone',
    'PhoneNumber': '983-4293',
    'AreaCode': '613',
    'PhoneTypeId': '1'}],
  'Emails': [{'ContactId': '574232379'}],
  'Position': 'Salesperson',
  'PermitFreetextEmail': True,
  'FirstName': 'ELLIOTT',
  'LastName': 'CAMEL-TOUEG',
  'CorporationDisplayTypeId': '0',
  'PermitShowListingLink': True,
  'RelativeDetailsURL': '/agent/2148118/elliott-camel-toueg-58-hampton-ave-ottawa-ontario-k1y0n2',
  'RankMyAgentKey': '',
  'RealSatisfiedKey': '',
  'TestimonialTreeKey': ''}]